INSERT INTO application_properties ("application_property_id", "property_name", "property_value") VALUES (1, 'rest.url.sightEventsUpload', 'https://api.hello-poland.pl/v1/partner/sight-events');
INSERT INTO application_properties ("application_property_id", "property_name", "property_value") VALUES (2, 'ticket.booked.timeToBuy', '20');
INSERT INTO application_properties ("application_property_id", "property_name", "property_value") VALUES (3, 'ticket.qrCode.height', '200');
INSERT INTO application_properties ("application_property_id", "property_name", "property_value") VALUES (4, 'ticket.qrCode.width', '200');
INSERT INTO application_properties ("application_property_id", "property_name", "property_value") VALUES (5, 'jwt.accessTokenSecretKey', 'dktYYUUvcndwc3IrM2NNakRxSWJkdjdpZU9pUVQvNm1GUlRMYmhLNFpsMFQ0WjNpeTlCSDhsWCsrUDFjV2hNNytWTUpnT1E5aWJxRk1PWXVaS3RyNkl5UkhrVTJiL1BCcXVTZWNMeVVQN1FwOUxwM0hQT2JSbnkrQ08rTnJJRzU4VUdEU0wvdng0SGhNa2xDbGJZT2RVeDF4b0F1bDNYa2FraWYyb3dvbDAzcA==');
INSERT INTO application_properties ("application_property_id", "property_name", "property_value") VALUES (6, 'jwt.refreshTokenSecretKey', 'amUzNzN3bHcveUlNQ3cvOGYvcERZZ0UwZUdoY3pvZnJSbEFYT01aMHFvTkdFYm1UckxSQkpLNUVlNW8zVGx5RGZqTExYclF1emNaUkFNb2F4Wk03NGFBczdPWWdKYVROcVpnckh0eTdpV1ZtWm1STW5SYnRJWFFEWnlrKzFraVFoZFYvUjZqUTBBNTRmcHMrcTQyQlU1NE1oZlZQbWJtbEJkaHRscnMxZmVkRA==');
INSERT INTO application_properties ("application_property_id", "property_name", "property_value") VALUES (7, 'jwt.accessTokenValidityMillis', '1800000');
INSERT INTO application_properties ("application_property_id", "property_name", "property_value") VALUES (8, 'jwt.refreshTokenValidityMillis', '2592000000');
INSERT INTO application_properties ("application_property_id", "property_name", "property_value") VALUES (9, 'mail.ticket.copy', 'orders@hello-poland.pl');

INSERT INTO email_templates("email_template_id", "name", "subject", "template") VALUES (1, 'ticketQrCodeEmailTemplate', 'Potwierdzenie opłacenia rezerwacji', '<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width" /><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Ubuntu:regular,bold&subset=Latin-ext"><title>Simple Transactional Email</title><style type="text/css">body {background-color: #f6f6f6;font-family: Ubuntu, arial;-webkit-font-smoothing: antialiased;font-size: 14px;line-height: 1.4;margin: 0;padding: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;}div{margin: 20px;}.footer {width: 100%;color: #999999;text-align: center;font-size: 12px;}</style></head><body><div id="text"><p>Witaj ${userName},</p><p>Poni&#380;ej znajdziesz zakupione bilety. Sprawd&#378;, czy Organizator nie do&#322;&#261;czy&#322; do tego e-maila za&#322;&#261;cznika. Cz&#281;sto mo&#380;esz tam znale&#378;&#263; dodatkowe informacje o Ofercie oraz Regulamin Atrakcji dotycz&#261;cy &#347;wiadczenia us&#322;ug.</p></div><div id="tickets">${qrCodes}</div><div class="footer"><p class="apple-link">Hello Poland Sp. z o.o.</p></div></body></html>');
INSERT INTO email_templates("email_template_id", "name", "subject", "template") VALUES (2, 'ticketQrCodeTemplate', 'Zakupiony Bilet', '<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width" /><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Ubuntu:regular,bold&subset=Latin-ext"><style type="text/css">body {background-color: #f6f6f6;font-family: Ubuntu, arial;-webkit-font-smoothing: antialiased;font-size: 14px;line-height: 1.4;margin: 0;padding: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;}table {background-color: white;border-collapse: collapse;border-color: #ff0026;border-width: 3px;border-style: solid;text-align: center;table-layout: fixed;width: 680px;margin: 30px auto;}td {border-color: #ff0026;border-width: 1px;border-style: dotted;padding: 5px;}.text-red {color: #ff0026;}.text-left {text-align: left;}.word-break {word-wrap: break-word;}</style></head><body><table><colgroup><col width="18%"><col width="68%"></colgroup><tr class="text-left"><td class="text-red">Numer transakcji:</td><td colspan="2">${P24_transactionNumber}</td></tr><tr class="text-left"><td class="text-red">Wydarzenie:</td><td colspan="2">${sightEventName}</td></tr><tr class="text-left"><td class="text-red">Data/godzina:</td><td colspan="2">${sightEventDate}</td></tr><tr><td colspan="3">${qrCode}</td></tr><tr><td><span class="text-red">Bilet:</span><br>${ticketName}</td><td class="word-break"><span class="text-red">Numer Biletu:</span><br>${ticketNumber}</td><td><span class="text-red">Cena:</span><br>${ticketPrice}</td></tr><tr><td class="text-red" colspan="3">Sprawd&#378;, czy Organizator nie do&#322;&#261;czy&#322; do tego e-maila za&#322;&#261;cznika. Cz&#281;sto mo&#380;esz tam znale&#378;&#263; dodatkowe informacje o Wydarzeniu.</td></tr></table></body></html>');

SELECT setval('application_properties_application_property_id_seq', (SELECT max(application_property_id) FROM application_properties));
SELECT setval('email_templates_email_template_id_seq', (SELECT max(email_template_id) FROM email_templates));
