INSERT INTO application_properties ("application_property_id", "property_name", "property_value") VALUES (1, 'rest.url.sightEventsUpload', 'https://hpl.fream.pl/api/v1/partner/sight-events')
INSERT INTO application_properties ("application_property_id", "property_name", "property_value") VALUES (2, 'ticket.booked.timeToBuy', '20')
INSERT INTO application_properties ("application_property_id", "property_name", "property_value") VALUES (3, 'ticket.qrCode.height', '200')
INSERT INTO application_properties ("application_property_id", "property_name", "property_value") VALUES (4, 'ticket.qrCode.width', '200')
INSERT INTO application_properties ("application_property_id", "property_name", "property_value") VALUES (5, 'jwt.accessTokenSecretKey', 'jV&SG6oL1>NTFlnW:l+PZmxX+^?gG`pNrX]@7LvX}e_IuoAx#:Wm#]$(_?{R^k8')
INSERT INTO application_properties ("application_property_id", "property_name", "property_value") VALUES (6, 'jwt.refreshTokenSecretKey', 'q!WJ$HlU}7%IOu;(f:7Z`j[{qq$R;5)g7^CBm48{f#6W27<$SJy+xw[{x3SfZmO')
INSERT INTO application_properties ("application_property_id", "property_name", "property_value") VALUES (7, 'jwt.accessTokenValidityMillis', '1800000')
INSERT INTO application_properties ("application_property_id", "property_name", "property_value") VALUES (8, 'jwt.refreshTokenValidityMillis', '2592000000')
INSERT INTO application_properties ("application_property_id", "property_name", "property_value") VALUES (9, 'mail.ticket.copy', 'dawidsokip@gmail.com')

INSERT INTO email_templates("email_template_id", "name", "subject", "template") VALUES (1, 'ticketQrCodeEmailTemplate', 'Potwierdzenie opłacenia rezerwacji', '<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width" /><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Ubuntu:regular,bold&subset=Latin-ext"><title>Simple Transactional Email</title><style type="text/css">body {background-color: #f6f6f6;font-family: Ubuntu, arial;-webkit-font-smoothing: antialiased;font-size: 14px;line-height: 1.4;margin: 0;padding: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;}div{margin: 20px;}.footer {width: 100%;color: #999999;text-align: center;font-size: 12px;}</style></head><body><div id="text"><p>Witaj ${userName},</p><p>Poni&#380;ej znajdziesz zakupione bilety. Sprawd&#378;, czy Organizator nie doda&#322; informacji dodatkowych o Wydarzeniu - je&#347;li tak, to znajdziesz je w za&#322;&#261;czniku.</p></div><div id="tickets">${qrCodes}</div><div class="footer"><p class="apple-link">Hello Poland Sp. z o.o.</p><p class="powered-by">Powered by Fream S.A.</p></div></body></html>')
INSERT INTO email_templates("email_template_id", "name", "subject", "template") VALUES (2, 'ticketQrCodeTemplate', 'Zakupiony Bilet', '<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width" /><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Ubuntu:regular,bold&subset=Latin-ext"><style type="text/css">body {background-color: #f6f6f6;font-family: Ubuntu, arial;-webkit-font-smoothing: antialiased;font-size: 14px;line-height: 1.4;margin: 0;padding: 0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;}table {background-color: white;border-collapse: collapse;border-color: #ff0026;border-width: 3px;border-style: solid;text-align: center;table-layout: fixed;width: 680px;margin: 30px auto;}td {border-color: #ff0026;border-width: 1px;border-style: dotted;padding: 5px;}.text-red {color: #ff0026;}.text-left {text-align: left;}.word-break {word-wrap: break-word;}</style></head><body><table><colgroup><col width="18%"><col width="68%"></colgroup><tr class="text-left"><td class="text-red">Numer transakcji:</td><td colspan="2">${P24_transactionNumber}</td></tr><tr class="text-left"><td class="text-red">Wydarzenie:</td><td colspan="2">${sightEventName}</td></tr><tr class="text-left"><td class="text-red">Data/godzina:</td><td colspan="2">${sightEventDate}</td></tr><tr><td colspan="3">${qrCode}</td></tr><tr><td><span class="text-red">Bilet:</span><br>${ticketName}</td><td class="word-break"><span class="text-red">Numer Biletu:</span><br>${ticketNumber}</td><td><span class="text-red">Cena:</span><br>${ticketPrice}</td></tr><tr><td class="text-red" colspan="3">Sprawd&#378;, czy Organizator nie do&#322;&#261;czy&#322; do tego e-maila za&#322;&#261;cznika. Cz&#281;sto mo&#380;esz tam znale&#378;&#263; dodatkowe informacje o Wydarzeniu.</td></tr></table></body></html>')

INSERT INTO partners("partner_id", "name", "email") VALUES (1, 'Hello Poland Partner', 'HelloPoland@HelloPoland.com')
INSERT INTO partners("partner_id", "name", "email") VALUES (2, 'Zoo', 'Zoo@HelloPoland.com')
INSERT INTO partners("partner_id", "name", "email") VALUES (3, 'Kolejkowo', 'Kolejkowo@HelloPoland.com')
INSERT INTO partners("partner_id", "name", "email") VALUES (4, 'Stadion Gdański', 'StadionGdański@HelloPoland.com')

INSERT INTO users("user_id", "name", "email", "password", "token", "hidden") VALUES (1, 'hp-admin', 'hp-admin@fream.pl', '$2a$10$GxfKZgXMj8xsvFrnqQqfAePh0eTozeIVZit.1HnSmNK6RCr7nqPem', 'eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJocC1hZG1pbkBmcmVhbS5wbCIsImF1dGgiOiJST0xFX0FETUlOIn0.ffo2GsvkbE72S4BMWEoXs2ZV9PIBkTaiFKX7DQr_Xm0pxXMrWSzI8TICovtwvi4RdEzsX4Xty8DNKXvkP12ciw', FALSE)
INSERT INTO users("user_id", "name", "email", "partner_id", "password", "token", "hidden") VALUES (2, 'hp-partner', 'hp-partner@fream.pl', 1, '$2a$10$6WCGp2osNlwTv.bKYcZoOeU3XTwkR1Ron54d9j3fV7h1h0HBuiZBi', 'eyJhbGciOiJub25lIn0.eyJzdWIiOiI1RDU1NTEwOURBM0Y5RUQwMEVFRkQyNTY2MDMwRUQ3MjJBNEQ3NzAwREU2MDA2NjQ5NzhBNjIwOTRCNUVFN0Y0In0.', TRUE)
INSERT INTO users("user_id", "name", "email", "partner_id", "password", "token", "hidden") VALUES (3, 'Zoo', 'zoo@zoo.plQQ', 2, '$2a$10$cJTmPp0glypoxqq.WkUzCeLGClwGGL2bFszZ/moMoSVK6EYqiXlgK', 'eyJhbGciOiJub25lIn0.eyJzdWIiOiJDOTU1NTI0MDk2REU0MjlEQjBGODM1NTA1RUI5MzAxNzkzQzE4NEJBQzM2NTFBNzI2MDFCRDNGMUFEQTkyQzAzIn0.', TRUE)
INSERT INTO users("user_id", "name", "email", "partner_id", "password", "token", "hidden") VALUES (4, 'Kolejkowo', 'kolejkowo@kolejkowo.plQQ', 3, '$2a$10$TGAWxJyrfdD7o/fR1ga33.0I/OjJAHuxZFXStsRkNNZO3IFwr4GGG', 'eyJhbGciOiJub25lIn0.eyJzdWIiOiI0MDc5MTkyRkI2NTQyQTYyRjc3QTcwNDZDRDU1QkJGNUM5NDAzNkE0MjRFRDI4RTM0MEYwODNCRDE1MDRFODZBIn0.', TRUE)
INSERT INTO users("user_id", "name", "email", "partner_id", "password", "token", "hidden") VALUES (5, 'Stadion Gdański', 'stadiongdansk@stadiongdansk.plQQ', 4, '$2a$10$IyUmTkbXKsUyQS42wYHP9ebHY4/MPoOE7hxERyiJrLtxGHQ/JnUzW', 'eyJhbGciOiJub25lIn0.eyJzdWIiOiIyODQyODcyRThEQ0EzMENFNkJBOTk5REMzQjBGODJFNUNFOTNFNzA5RTJEMjlGMEQ4NjFFOTU4QjMxQ0QwQzREIn0.', TRUE)
INSERT INTO users("user_id", "name", "email", "partner_id", "password", "hidden") VALUES (6, 'hp-bileter', 'hp-bileter@fream.pl', 1, '$2a$10$VZ03rNmPD10EbCQTgLQzr.XX0hCtH7Q2fx2ly2vMKL9V/m6ojNJl.', FALSE)
INSERT INTO users("user_id", "name", "email", "partner_id", "password", "hidden") VALUES (7, 'hp-bileter-example1', 'hp-bileter-example1@example.com', 1, '$2a$10$Vu4dEYIzkYQxzVkFPhkMRuI35LKwLanNNYF99Gi87.9agRtN7hSX2', FALSE)
INSERT INTO users("user_id", "name", "email", "partner_id", "password", "hidden") VALUES (8, 'hp-bileter-example2', 'hp-bileter-example2@example.com', 1, '$2a$10$uJiZwSFleMeCXupBvscGsO7GWkUFihTCTtPMBv4zNtK8HjWjvRqE6', FALSE)

INSERT INTO user_authorities("user_user_id", "authorities") VALUES (1, 'ROLE_ADMIN')
INSERT INTO user_authorities("user_user_id", "authorities") VALUES (2, 'ROLE_EXTERNAL_USER')
INSERT INTO user_authorities("user_user_id", "authorities") VALUES (2, 'ROLE_USHER')
INSERT INTO user_authorities("user_user_id", "authorities") VALUES (3, 'ROLE_EXTERNAL_USER')
INSERT INTO user_authorities("user_user_id", "authorities") VALUES (3, 'ROLE_USHER')
INSERT INTO user_authorities("user_user_id", "authorities") VALUES (4, 'ROLE_EXTERNAL_USER')
INSERT INTO user_authorities("user_user_id", "authorities") VALUES (4, 'ROLE_USHER')
INSERT INTO user_authorities("user_user_id", "authorities") VALUES (5, 'ROLE_EXTERNAL_USER')
INSERT INTO user_authorities("user_user_id", "authorities") VALUES (5, 'ROLE_USHER')
INSERT INTO user_authorities("user_user_id", "authorities") VALUES (6, 'ROLE_USHER')
INSERT INTO user_authorities("user_user_id", "authorities") VALUES (7, 'ROLE_USHER')
INSERT INTO user_authorities("user_user_id", "authorities") VALUES (8, 'ROLE_USHER')

SELECT setval('application_properties_application_property_id_seq', (SELECT max(application_property_id) FROM application_properties))
SELECT setval('bookings_booking_id_seq', (SELECT max(booking_id) FROM bookings))
SELECT setval('email_templates_email_template_id_seq', (SELECT max(email_template_id) FROM email_templates))
SELECT setval('expired_tokens_expired_token_id_seq', (SELECT max(expired_token_id) FROM expired_tokens))
SELECT setval('partners_partner_id_seq', (SELECT max(partner_id) FROM partners))
SELECT setval('sight_events_sight_event_id_seq', (SELECT max(sight_event_id) FROM sight_events))
SELECT setval('ticket_definitions_ticket_definition_id_seq', (SELECT max(ticket_definition_id) FROM ticket_definitions))
SELECT setval('ticket_pool_definitions_ticket_pool_definition_id_seq', (SELECT max(ticket_pool_definition_id) FROM ticket_pool_definitions))
SELECT setval('ticket_pools_ticket_pool_id_seq', (SELECT max(ticket_pool_id) FROM ticket_pools))
SELECT setval('tickets_ticket_id_seq', (SELECT max(ticket_id) FROM tickets))
SELECT setval('users_user_id_seq', (SELECT max(user_id) FROM users))