hibernate.hbm2ddl.auto=update
javax.persistence.sql-load-script-source=
javax.persistence.jdbc.host=localhost
javax.persistence.jdbc.port=5432
javax.persistence.jdbc.database=helloticket
javax.persistence.jdbc.user=helloticket
javax.persistence.jdbc.password=helloticket
