hibernate.hbm2ddl.auto=update
jakarta.persistence.sql-load-script-source=
jakarta.persistence.jdbc.host=172.17.0.1
jakarta.persistence.jdbc.port=5432
jakarta.persistence.jdbc.database=helloticket
jakarta.persistence.jdbc.user=helloticket
jakarta.persistence.jdbc.password=hpt-prod
