mail.username=hpt@fream.pl
mail.password=JbmU4lMo
mail.smtp.host=s43.linuxpl.com
mail.smtp.port=465
mail.smtp.auth=true
mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
resteasy.preferJacksonOverJsonB=false

#prod
#mail.hellopoland.biuro=biuro@hello-poland.pl
#test
#mail.hellopoland.biuro=dawidsokip@gmail.com
mail.hellopoland.biuro=wwolakksiazek@gmail.com
