mail.personal=Hello! Poland. - Bilety
mail.smtp.enabled=true
mail.username=tickets@hello-poland.pl
mail.password=Fm{d56Hpl3o%
mail.smtp.host=hellopoland.nazwa.pl
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.hellopoland.biuro=tickets@hello-poland.pl
#mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
resteasy.preferJacksonOverJsonB=false
pool.entry.date.repairer.enabled=false
mail.ticket.backup=orders@hello-poland.pl
mail.hellopoland.helpdesk=helpdesk@hello-poland.pl