mail.personal=Bilety Hello Poland
mail.smtp.enabled=true
mail.username=helpdesk@coigdzie.eu
mail.password=H3ll0!pol4nd2024
mail.smtp.host=serwer2421980.home.pl
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
#mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
resteasy.preferJacksonOverJsonB=false
mail.hellopoland.biuro=helpdesk@coigdzie.eu
pool.entry.date.repairer.enabled=false