datasource.database.host=localhost
datasource.database.port=5432
datasource.database.name=hellopolandticket
datasource.database.user=hellopolandticket
datasource.database.password=hellopolandticket

hibernate.hbm2ddl.auto=create
javax.persistence.sql-load-script-source=META-INF/import.sql