datasource.database.host=localhost
datasource.database.port=5432
datasource.database.name=hellopolandticket
datasource.database.user=hellopolandticket
datasource.database.password=hellopolandticket

hibernate.hbm2ddl.auto=
#javax.persistence.sql-load-script-source=META-INF/import.sql
javax.persistence.sql-load-script-source=

mail.username=hpt@fream.pl
mail.password=JbmU4lMo
mail.smtp.host=s43.linuxpl.com
mail.smtp.port=465
mail.smtp.auth=true
mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
