datasource.database.host=localhost
datasource.database.port=5432
datasource.database.name=hellopolandticket
datasource.database.user=hellopolandticket
datasource.database.password=hellopolandticket

javax.persistence.schema-generation.database.action=drop-and-create
javax.persistence.sql-load-script-source=META-INF/import.sql