datasource.database.name=helloticket
datasource.database.user=helloticket
datasource.database.password=tralalala123

wildfly.home=/home/hpt/usr/wildfly

mail.username=tickets@hello-poland.pl
mail.password=gr34td34lHP
mail.smtp.host=hellopoland.nazwa.pl
mail.smtp.port=25
mail.smtp.auth=true
mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory