datasource.database.name=helloticket
datasource.database.user=helloticket
datasource.database.password=tralalala123

hibernate.hbm2ddl.auto=create
javax.persistence.sql-load-script-source=META-INF/import-test-server.sql

wildfly.home=/home/hpt/usr/wildfly