datasource.database.name=hptbeta
datasource.database.user=hptbeta
datasource.database.password=kbuaYZHfaT8NCDSf

hibernate.hbm2ddl.auto=create
javax.persistence.sql-load-script-source=META-INF/import-prod-server.sql

wildfly.home=/home/hptbeta/usr/wildfly