wildfly.home=C:\\Users\\kret\\workspaces\\HelloPoland\\HPT\\wildfly-14.0.0.Final
dms.root.path=C:\\Users\\kret\\workspaces\\HelloPoland\\HPT\\DMS
hibernate.hbm2ddl.auto=update

jwt.access.token.validity.millis=300000
jwt.refresh.token.validity.millis=300000