wildfly.home=C:\\Users\\kret\\workspaces\\HelloPoland\\2-wildfly-14.0.1.Final

hibernate.hbm2ddl.auto=update

datasource.database.name=helloticket
datasource.database.user=helloticket
datasource.database.password=helloticket