wildfly.home=C:\\Users\\kret\\workspaces\\HelloPoland\\2-wildfly-14.0.1.Final

hibernate.hbm2ddl.auto=update

javax.persistence.jdbc.host=localhost
javax.persistence.jdbc.port=5432
javax.persistence.jdbc.database=hpt_test
javax.persistence.jdbc.user=hpt_test
javax.persistence.jdbc.password=hpt_test
