wildfly.home=C:\\Users\\lmrozek\\eclipse-workspace\\hpt\\wildfly-14.0.0.Final

datasource.database.name=hellopoland_hpt
datasource.database.user=hellopoland_hpt
datasource.database.password=hellopoland_hpt

hibernate.hbm2ddl.auto=create
hibernate.show.sql=true
#javax.persistence.sql-load-script-source=
javax.persistence.sql-load-script-source=META-INF/import-test-server.sql