wildfly.home=C:\\Users\\lmrozek\\eclipse-workspace\\hpt\\wildfly-14.0.0.Final
helpdesk.log.dir=C:\\Users\\lmrozek\\eclipse-workspace\\hpt\\helpdesk_log

datasource.database.name=hellopoland_hpt
datasource.database.user=hellopoland_hpt
datasource.database.password=hellopoland_hpt