<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>pl.hellopoland</groupId>
		<artifactId>hellopoland-ticket</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<artifactId>hellopoland-ticket-app</artifactId>
	<packaging>war</packaging>

	<dependencies>
		<dependency>
			<groupId>pl.hellopoland</groupId>
			<artifactId>hellopoland-ticket-rest</artifactId>
			<type>jar</type>
		</dependency>
		<dependency>
			<groupId>pl.hellopoland</groupId>
			<artifactId>hellopoland-ticket-service</artifactId>
			<type>jar</type>
		</dependency>
		<dependency>
			<groupId>pl.hellopoland</groupId>
			<artifactId>hellopoland-ticket-dao</artifactId>
			<type>jar</type>
		</dependency>

		<dependency>
			<groupId>pl.hellopoland</groupId>
			<artifactId>hellopoland-dto</artifactId>
			<version>0.0.2-SNAPSHOT</version>
		</dependency>
	</dependencies>

	<repositories>
		<repository>
			<id>fream-nexus</id>
			<url>https://packages.fream.pl/repository/maven-fream-snapshots</url>
		</repository>
	</repositories>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<version>3.2.0</version>
				<configuration>
					<modules>
						<webModule>
							<groupId>pl.hellopoland</groupId>
							<artifactId>hellopoland-ticket-rest</artifactId>
							<contextRoot>/api</contextRoot>
						</webModule>
					</modules>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>